version: '3.8'

services:
  web:
    image: host:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"

  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "Senhaforte123@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./sql-scripts:/docker-entrypoint-initdb.d